sudo: required

services:
- docker

script:
- export RUN_ARGS="--rm --privileged -v /lib/modules/:/lib/modules/ -v $(pwd):/etc/ansible/roles/v2ray/"
- export PLAYBOOK="-i /etc/ansible/roles/v2ray/tests/inventory /etc/ansible/roles/v2ray/tests/test.yml"

- docker run $RUN_ARGS indexyz/ansible:debian-9 $PLAYBOOK
- docker run $RUN_ARGS indexyz/ansible:centos-7 $PLAYBOOK

notifications:
 webhooks: https://galaxy.ansible.com/api/v1/notifications/
