---
# tasks file for v2ray
- include: dependencies/{{ ansible_distribution | lower }}.yml
  tags:
    - install
    - deps

- import_tasks: prepare.yml
  tags:
    - install
    - prepre

- import_tasks: tarbar.yml
  tags:
    - install

- import_tasks: install.yml
  tags:
    - install

- import_tasks: config.yml
  tags:
    - config

- import_tasks: tls.yml
  tags:
    - config
  when: tls.enable

- import_tasks: test.yml
  tags:
    - test
  when: test_mode is defined
