---
# tasks file for v2ray
- import_tasks: prepare.yml
  tags:
    - install
    - prepre

- import_tasks: tarbar.yml
  tags:
    - install

- import_tasks: install.yml
  tags:
    - install

- import_tasks: config.yml
  tags:
    - config
