---
- name: Create v2ray dir
  file:
    path: "{{install_location}}"
    state: directory

- name: Create v2ray app dir
  file:
    path: "{{install_location}}/app"
    state: directory

- name: Create v2ray cert dir
  file:
    path: "{{install_location}}/cert"
    state: directory
  when: tls.enable
