---
# handlers file for v2ray
- name: start v2ray
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: v2ray
  # Docker is not support systemd
  # http://syste.md ;-(
  when: test_mode is not defined
